<div class="bg-[var(--background-color)]">
  <div class="mx-auto px-4 md:px-8 pt-16 text-center">
    <h2 class="text-2xl font-heading">Comedians who have supported us include:</h2>
  </div>
  <div class="swiper comedians-swiper font-regular-light">
    <div class="swiper-wrapper mb-4">
      <div class="swiper-slide text-2xl sm:text-6xl w-auto ">ADAM ROWE</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">AMY SCHUMER</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">ANDI OSHO</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">ANDY PARSONS</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">AISLING BEA</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">AXEL BLAKE</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">AZIZ ANSARI</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">CHRIS ROCK</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">ED BYRNE. CHRIS DISTEFANO</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">DALISO CHAPONDA</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">DARA O BRIAIN</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">DAVE CHAPPELLE</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">DAVID MCSAVAGE</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">DULCÉ SLOAN</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">DYLAN MORAN</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">EDDIE IZZARD</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">ELLIE TAYLOR</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">HOLLY WALSH</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">ISY SUTTIE</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">JACK WHITEHALL</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">JAMALI MADDIX. JASON MANFORD</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">JAMES ACASTER</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">JEFF GARLIN. JEREMY PIVEN. JOE LIST</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">JOE WILKINSON. JOHN BISHOP</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">JAMALI MADDIX. JOANNE MCNALLY</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">JOE LYCETT</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">JOE WILKINSON</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">JOEL DOMMETT. JOSH WIDDICOMBE</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">JUDAH FRIEDLANDER</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">KATHERINE RYAN</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">KERRY GODLIMAN</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">KEVIN BRIDGES, LEE NELSON</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">LOUISA OMIELAN. LOYISO GOLA</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">MICHAEL MCINTYRE, MICHELLE DE SWARTE</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">MICKY FLANAGAN</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">NABIL ABDUL RASHID</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">NIGEL NG</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">OMID DJALILI</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">PAUL CHOWDHRY. PHIL WANG</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">REGINALD D HUNTER</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">RICH HALL</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">ROB BECKETT. ROMESH RANGANATHAN</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">ROSS NOBLE</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">RUSSELL HOWARD</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">SARA PASCOE</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">SEANN WALSH</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">SIMON AMSTELL. SIMON BRODKIN</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">SINDHU VEE</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">STEPHEN K AMOS</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">STEPHEN MERCHANT</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">TOM ALLEN</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">TREVOR NOAH</div>
      <div class="swiper-slide text-2xl sm:text-6xl w-auto">VIR DAS</div>
    </div>
  </div>
</div>
