<div class="bg-[var(--secondary-color)]">
  <div class="mx-auto px-4 md:px-8 pt-16 text-center">
    <h2 class="text-2xl font-bold">Comedians who have supported us include:</h2>
  </div>
  <div class="swiper comedians-swiper">
    <div class="swiper-wrapper">
      <div class="swiper-slide text-xl font-semibold">ADAM ROWE</div>
      <div class="swiper-slide text-xl font-semibold">AMY SCHUMER</div>
      <div class="swiper-slide text-xl font-semibold">ANDI OSHO</div>
      <div class="swiper-slide text-xl font-semibold">ANDY PARSONS</div>
      <div class="swiper-slide text-xl font-semibold">AISLING BEA</div>
      <div class="swiper-slide text-xl font-semibold">AXEL BLAKE</div>
      <div class="swiper-slide text-xl font-semibold">AZIZ ANSARI</div>
      <div class="swiper-slide text-xl font-semibold">CHRIS ROCK</div>
      <div class="swiper-slide text-xl font-semibold">ED BYRNE. CHRIS DISTEFANO</div>
      <div class="swiper-slide text-xl font-semibold">DALISO CHAPONDA</div>
      <div class="swiper-slide text-xl font-semibold">DARA O BRIAIN</div>
      <div class="swiper-slide text-xl font-semibold">DAVE CHAPPELLE</div>
      <div class="swiper-slide text-xl font-semibold">DAVID MCSAVAGE</div>
      <div class="swiper-slide text-xl font-semibold">DULCÉ SLOAN</div>
      <div class="swiper-slide text-xl font-semibold">DYLAN MORAN</div>
      <div class="swiper-slide text-xl font-semibold">EDDIE IZZARD</div>
      <div class="swiper-slide text-xl font-semibold">ELLIE TAYLOR</div>
      <div class="swiper-slide text-xl font-semibold">HOLLY WALSH</div>
      <div class="swiper-slide text-xl font-semibold">ISY SUTTIE</div>
      <div class="swiper-slide text-xl font-semibold">JACK WHITEHALL</div>
      <div class="swiper-slide text-xl font-semibold">JAMALI MADDIX. JASON MANFORD</div>
      <div class="swiper-slide text-xl font-semibold">JAMES ACASTER</div>
      <div class="swiper-slide text-xl font-semibold">JEFF GARLIN. JEREMY PIVEN. JOE LIST</div>
      <div class="swiper-slide text-xl font-semibold">JOE WILKINSON. JOHN BISHOP</div>
      <div class="swiper-slide text-xl font-semibold">JAMALI MADDIX. JOANNE MCNALLY</div>
      <div class="swiper-slide text-xl font-semibold">JOE LYCETT</div>
      <div class="swiper-slide text-xl font-semibold">JOE WILKINSON</div>
      <div class="swiper-slide text-xl font-semibold">JOEL DOMMETT. JOSH WIDDICOMBE</div>
      <div class="swiper-slide text-xl font-semibold">JUDAH FRIEDLANDER</div>
      <div class="swiper-slide text-xl font-semibold">KATHERINE RYAN</div>
      <div class="swiper-slide text-xl font-semibold">KERRY GODLIMAN</div>
      <div class="swiper-slide text-xl font-semibold">KEVIN BRIDGES, LEE NELSON</div>
      <div class="swiper-slide text-xl font-semibold">LOUISA OMIELAN. LOYISO GOLA</div>
      <div class="swiper-slide text-xl font-semibold">MICHAEL MCINTYRE, MICHELLE DE SWARTE</div>
      <div class="swiper-slide text-xl font-semibold">MICKY FLANAGAN</div>
      <div class="swiper-slide text-xl font-semibold">NABIL ABDUL RASHID</div>
      <div class="swiper-slide text-xl font-semibold">NIGEL NG</div>
      <div class="swiper-slide text-xl font-semibold">OMID DJALILI</div>
      <div class="swiper-slide text-xl font-semibold">PAUL CHOWDHRY. PHIL WANG</div>
      <div class="swiper-slide text-xl font-semibold">REGINALD D HUNTER</div>
      <div class="swiper-slide text-xl font-semibold">RICH HALL</div>
      <div class="swiper-slide text-xl font-semibold">ROB BECKETT. ROMESH RANGANATHAN</div>
      <div class="swiper-slide text-xl font-semibold">ROSS NOBLE</div>
      <div class="swiper-slide text-xl font-semibold">RUSSELL HOWARD</div>
      <div class="swiper-slide text-xl font-semibold">SARA PASCOE</div>
      <div class="swiper-slide text-xl font-semibold">SEANN WALSH</div>
      <div class="swiper-slide text-xl font-semibold">SIMON AMSTELL. SIMON BRODKIN</div>
      <div class="swiper-slide text-xl font-semibold">SINDHU VEE</div>
      <div class="swiper-slide text-xl font-semibold">STEPHEN K AMOS</div>
      <div class="swiper-slide text-xl font-semibold">STEPHEN MERCHANT</div>
      <div class="swiper-slide text-xl font-semibold">TOM ALLEN</div>
      <div class="swiper-slide text-xl font-semibold">TREVOR NOAH</div>
      <div class="swiper-slide text-xl font-semibold">VIR DAS</div>
    </div>
  </div>
</div>
